#!/usr/bin/env pwsh
[CmdletBinding(PositionalBinding=$false)]
param(
    [Parameter(Mandatory=$false)]
    [Alias('c')]
    [string]$Config,

    [Parameter(Mandatory=$true)]
    [Alias('f')]
    [string[]]$File
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$script:AutoGeneratedPairs = @()

function Read-IniSections {
    param([string]$Path)

    if (-not (Test-Path -Path $Path -PathType Leaf)) {
        throw "Config file '$Path' not found."
    }

    $stack = New-Object System.Collections.Generic.List[string]
    $orderList = New-Object System.Collections.Generic.List[pscustomobject]
    $sectionList = Parse-IniSections -Path $Path -Stack $stack -OrderList $orderList
    $sections = [ordered]@{}
    foreach ($section in $sectionList) {
        $sections[$section.name] = $section.data
    }

    return [pscustomobject]@{
        map = $sections
        order = $orderList
    }
}

function Parse-IniSections {
    param(
        [string]$Path,
        [System.Collections.Generic.List[string]]$Stack,
        [System.Collections.Generic.List[pscustomobject]]$OrderList
    )

    $resolved = Resolve-Path -Path $Path -ErrorAction Stop | Select-Object -First 1 -ExpandProperty ProviderPath
    $resolved = [System.IO.Path]::GetFullPath($resolved)
    if ($Stack.Contains($resolved)) {
        throw "Include loop detected for '$resolved'."
    }
    $Stack.Add($resolved)

    $baseDir = Split-Path -Path $resolved -Parent
    $sections = New-Object System.Collections.Generic.List[object]
    $currentName = ''
    $currentData = [ordered]@{}
    $lines = Get-Content -Path $resolved -ErrorAction Stop

    function Add-Section {
        param(
            [System.Collections.Generic.List[object]]$List,
            [string]$Name,
            [hashtable]$Data,
            [string]$Source,
            [System.Collections.Generic.List[pscustomobject]]$OrderRef
        )
        if ([string]::IsNullOrEmpty($Name)) { return }
        $List.Add([pscustomobject]@{
            name = $Name
            data = $Data
            source = $Source
        })
        if ($OrderRef) {
            $OrderRef.Add([pscustomobject]@{
                kind = 'section'
                name = $Name
            })
        }
    }

    foreach ($line in $lines) {
        $trimmed = $line.Trim()
        if ($trimmed.Length -eq 0 -or $trimmed.StartsWith('#') -or $trimmed.StartsWith(';')) {
            continue
        }
        if ($trimmed.StartsWith('[') -and $trimmed.EndsWith(']')) {
            Add-Section -List $sections -Name $currentName -Data $currentData -Source $resolved -OrderRef $OrderList
            $currentName = $trimmed.Substring(1, $trimmed.Length - 2).Trim()
            $currentData = [ordered]@{}
            continue
        }
        $splitIndex = $line.IndexOf('=')
        if ($splitIndex -lt 0) {
            continue
        }
        $key = $line.Substring(0, $splitIndex).Trim()
        $value = $line.Substring($splitIndex + 1).Trim()
        $currentData[$key] = $value
    }
    Add-Section -List $sections -Name $currentName -Data $currentData -Source $resolved -OrderRef $OrderList

    for ($i = 0; $i -lt $sections.Count; ) {
        $entry = $sections[$i]
        if ($entry.name -like 'include.*') {
            $includeName = if ($entry.name.Length -gt 8) { $entry.name.Substring(8) } else { '' }
            $rawIncludeFile = if ($entry.data.Contains('include_file')) { $entry.data['include_file'] } else { $null }
            $includeFile = $rawIncludeFile
            if (-not $includeFile) {
                if (-not [string]::IsNullOrEmpty($includeName)) {
                    $includeFile = "$includeName.ini"
                } else {
                    throw "Include section '$($entry.name)' missing include_file and include name."
                }
            }
            if ([string]::IsNullOrWhiteSpace($includeFile)) {
                throw "Include section '$($entry.name)' has empty include_file."
            }
            $sectionDisabled = Get-SectionDisabledFlag -Section $entry.data
            $resolvedInclude = if ([System.IO.Path]::IsPathRooted($includeFile)) {
                [System.IO.Path]::GetFullPath($includeFile)
            } else {
                [System.IO.Path]::GetFullPath((Join-Path -Path $baseDir -ChildPath $includeFile))
            }
            if (-not (Test-Path -Path $resolvedInclude -PathType Leaf)) {
                throw "Included config '$resolvedInclude' not found (referenced by '$($entry.name)')."
            }
            $OrderList.Add([pscustomobject]@{
                kind = 'include'
                name = $entry.name
                include_file = $rawIncludeFile
                implicit = -not [bool]$rawIncludeFile
                resolved_path = $resolvedInclude
                disabled = $sectionDisabled
            })
            $sections.RemoveAt($i)
            if ($sectionDisabled) {
                continue
            }
            $childSections = Parse-IniSections -Path $resolvedInclude -Stack $Stack -OrderList $OrderList
            for ($j = $childSections.Count - 1; $j -ge 0; $j--) {
                $sections.Insert($i, $childSections[$j])
            }
            continue
        }
        $i++
    }

    $Stack.RemoveAt($Stack.Count - 1)
    return $sections
}

function ConvertTo-List {
    param([string]$Value)

    if ([string]::IsNullOrWhiteSpace($Value)) {
        return @()
    }

    return $Value.Split(',', [System.StringSplitOptions]::RemoveEmptyEntries) |
        ForEach-Object { $_.Trim() } |
        Where-Object { $_ -ne '' }
}

function ConvertTo-BooleanValue {
    param([string]$Value)

    if ($null -eq $Value) {
        return $false
    }
    $text = $Value.ToString().Trim().ToLowerInvariant()
    if ($text -eq '') { return $false }
    switch ($text) {
        'true' { return $true }
        '1' { return $true }
        'yes' { return $true }
        'on' { return $true }
        'false' { return $false }
        '0' { return $false }
        'no' { return $false }
        'off' { return $false }
        default { return $false }
    }
}

function Get-SectionDisabledFlag {
    param([hashtable]$Section)

    if (-not $Section) { return $false }
    if ($Section.Contains('enabled')) {
        $enabled = ConvertTo-BooleanValue -Value $Section['enabled']
        return -not $enabled
    }
    if ($Section.Contains('disabled')) {
        return ConvertTo-BooleanValue -Value $Section['disabled']
    }
    return $false
}

function Test-ObjectDisabled {
    param($Object)

    if (-not $Object) { return $false }
    $psobj = $Object.PSObject
    if (-not $psobj) { return $false }
    $property = $psobj.Properties['disabled']
    if ($null -eq $property) { return $false }
    return [bool]$property.Value
}

function Parse-Assignments {
    param([string]$Value)

    $result = @()
    if ([string]::IsNullOrWhiteSpace($Value)) {
        return $result
    }

    $entries = ConvertTo-List -Value $Value
    foreach ($entry in $entries) {
        $parts = $entry.Split('|', 2)
        if ($parts.Count -ne 2) {
            continue
        }
        $original = $parts[0].Trim()
        $anonymized = $parts[1].Trim()
        if ($original -and $anonymized) {
            $result += [pscustomobject]@{ original = $original; anonymized = $anonymized }
        }
    }

    return $result
}

function Find-FullPairByOriginal {
    param(
        [object[]]$Pairs,
        [string]$OriginalValue
    )

    if (-not $Pairs -or [string]::IsNullOrWhiteSpace($OriginalValue)) {
        return $null
    }

    foreach ($pair in $Pairs) {
        if (-not $pair) { continue }
        if ([string]::IsNullOrWhiteSpace($pair.original)) { continue }
        if ([string]::Equals($pair.original, $OriginalValue, [System.StringComparison]::OrdinalIgnoreCase)) {
            return $pair
        }
    }

    return $null
}

function Get-AutoFullName {
    param(
        [pscustomobject]$Config,
        [string]$OriginalValue
    )

    $slug = ($OriginalValue -replace '[^0-9A-Za-z]+', '-').Trim('-')
    if ([string]::IsNullOrWhiteSpace($slug)) {
        $slug = 'auto'
    }
    $base = "auto-$slug"
    $name = $base
    $suffix = 2
    while ($Config.pairs.full | Where-Object { $_.name -eq $name }) {
        $name = "{0}-{1}" -f $base, $suffix
        $suffix++
    }
    return $name
}

function Add-HintFullPair {
    param(
        [pscustomobject]$Config,
        [string]$OriginalValue,
        [string]$AnonymizedValue,
        [string]$SourceHint
    )

    $name = Get-AutoFullName -Config $Config -OriginalValue $OriginalValue
    $isAutoTarget = [bool]$Config.generated_pairs_file_path
    $pair = [pscustomobject]@{
        name = $name
        original = $OriginalValue
        anonymized = $AnonymizedValue
        from_auto = $isAutoTarget
        from_config = -not $isAutoTarget
        disabled = $false
    }
    $Config.pairs.full = @($Config.pairs.full + $pair)
    if ($Config.PSObject.Properties.Match('section_order')) {
        $Config.section_order += [pscustomobject]@{
            kind = 'section'
            name = "full.$name"
        }
    }
    $script:AutoGeneratedPairs += [pscustomobject]@{
        name = $name
        original = $OriginalValue
        anonymized = $AnonymizedValue
        source = $SourceHint
    }
    return $pair
}

function Write-GeneratedPairs {
    param(
        [object[]]$Entries,
        [string]$AutoFile
    )

    $lines = New-Object System.Collections.Generic.List[string]
    foreach ($entry in ($Entries | Sort-Object name)) {
        if (-not ($entry.original -and $entry.anonymized)) { continue }
        $lines.Add("[full.$($entry.name)]")
        $lines.Add("original=$($entry.original)")
        $lines.Add("anonymized=$($entry.anonymized)")
        if ($entry.source) {
            $lines.Add("source=$($entry.source)")
        }
        $lines.Add('')
    }

    $content = ($lines -join [Environment]::NewLine).TrimEnd()

    try {
        Set-Content -Path $AutoFile -Value $content
    }
    catch {
        throw "Unable to write generated entries file '$AutoFile': $($_.Exception.Message)"
    }
}

function Convert-HintAssignmentsToFull {
    param([pscustomobject]$Config)

    foreach ($hint in $Config.pairs.hints) {
        if (-not $hint) { continue }
        if (-not $hint.PSObject.Properties.Match('assignments')) { continue }
        foreach ($assignment in $hint.assignments) {
            if (-not ($assignment.original -and $assignment.anonymized)) { continue }
            $existing = Find-FullPairByOriginal -Pairs $Config.pairs.full -OriginalValue $assignment.original
            if (-not $existing) {
                Add-HintFullPair -Config $Config -OriginalValue $assignment.original -AnonymizedValue $assignment.anonymized -SourceHint $hint.name | Out-Null
            }
        }
        $hint.assignments = @()
    }
}

function Get-ConfigObject {
    param([string]$Path)

    $sectionResult = Read-IniSections -Path $Path
    $sections = $sectionResult.map
    $config = [pscustomobject]@{
        direction_markers = [pscustomobject]@{ original = @() }
        pairs = [pscustomobject]@{
            full = @()
            hints = @()
        }
        generated_pairs_file = $null
        generated_pairs_file_path = $null
        includes = @()
        section_order = @()
        extra_sections = @()
    }

    if ($sections.Keys -contains 'direction_markers') {
        $section = $sections['direction_markers']
        if ($section.Keys -contains 'original') {
            $config.direction_markers.original = ConvertTo-List -Value $section['original']
        }
    }

    if ($sections.Keys -contains 'global') {
        $globalSection = $sections['global']
        if ($globalSection.Keys -contains 'generated_entries_file') {
            $config.generated_pairs_file = $globalSection['generated_entries_file']
            $baseDir = Split-Path -Path $Path -Parent
            if ([string]::IsNullOrWhiteSpace($baseDir)) {
                $baseDir = (Get-Location).Path
            }
            if ([System.IO.Path]::IsPathRooted($config.generated_pairs_file)) {
                $config.generated_pairs_file_path = $config.generated_pairs_file
            } else {
                $config.generated_pairs_file_path = Join-Path -Path $baseDir -ChildPath $config.generated_pairs_file
            }
        }
    }

    foreach ($sectionName in $sections.Keys) {
        if ($sectionName -like 'full.*') {
            $name = $sectionName.Substring(5)
            if (-not $name) { $name = 'entry' }
            $section = $sections[$sectionName]
            $disabled = Get-SectionDisabledFlag -Section $section
            $config.pairs.full += [pscustomobject]@{
                name = $name
                original = if ($section.Keys -contains 'original') { $section['original'] } else { $null }
                anonymized = if ($section.Keys -contains 'anonymized') { $section['anonymized'] } else { $null }
                from_config = $true
                from_auto = $false
                disabled = $disabled
            }
        }
        elseif ($sectionName -like 'hint.*') {
            $name = $sectionName.Substring(5)
            if (-not $name) { $name = 'entry' }
            $section = $sections[$sectionName]
            $assignments = if ($section.Keys -contains 'assignments') { Parse-Assignments -Value $section['assignments'] } else { @() }
            $disabled = Get-SectionDisabledFlag -Section $section
            $hintObj = [pscustomobject]@{
                name = $name
                hint = if ($section.Keys -contains 'hint') { $section['hint'] } else { $null }
                prefix = if ($section.Keys -contains 'prefix') { $section['prefix'] } else { $null }
                postfix = if ($section.Keys -contains 'postfix') { $section['postfix'] } else { $null }
                width = if ($section.Keys -contains 'width') { [int]$section['width'] } else { $null }
                next_index = if ($section.Keys -contains 'next_index') { [int]$section['next_index'] } else { $null }
                randomize = if ($section.Keys -contains 'randomize') { [int]$section['randomize'] } elseif ($section.Keys -contains 'random_length') { [int]$section['random_length'] } else { $null }
                random_charset = if ($section.Keys -contains 'random_charset') { $section['random_charset'] } else { $null }
                assignments = $assignments
                disabled = $disabled
            }
            $config.pairs.hints += $hintObj
        }
    }

    $extraSections = New-Object System.Collections.Generic.List[pscustomobject]
    foreach ($sectionName in $sections.Keys) {
        if ($sectionName -eq 'direction_markers' -or $sectionName -eq 'global') { continue }
        if ($sectionName -like 'full.*' -or $sectionName -like 'hint.*' -or $sectionName -like 'include.*') { continue }
        $extraSections.Add([pscustomobject]@{
            name = $sectionName
            data = $sections[$sectionName]
        })
    }
    $config.extra_sections = $extraSections

    foreach ($orderEntry in $sectionResult.order) {
        switch ($orderEntry.kind) {
            'include' {
                $config.includes += [pscustomobject]@{
                    name = $orderEntry.name
                    include_file = $orderEntry.include_file
                    implicit = $orderEntry.implicit
                    disabled = $orderEntry.disabled
                }
                $config.section_order += [pscustomobject]@{
                    kind = 'include'
                    name = $orderEntry.name
                    include_file = $orderEntry.include_file
                    implicit = $orderEntry.implicit
                    disabled = $orderEntry.disabled
                }
            }
            Default {
                $config.section_order += [pscustomobject]@{
                    kind = 'section'
                    name = $orderEntry.name
                }
            }
        }
    }

    Convert-HintAssignmentsToFull -Config $config
    return $config
}

function Ensure-ConfigShape {
    param([pscustomobject]$Config)

    if (-not $Config.PSObject.Properties.Match('direction_markers')) {
        $Config | Add-Member -NotePropertyName 'direction_markers' -NotePropertyValue ([pscustomobject]@{original=@()})
    }
    elseif (-not $Config.direction_markers.PSObject.Properties.Match('original')) {
        $Config.direction_markers | Add-Member -NotePropertyName 'original' -NotePropertyValue @()
    }

    if (-not $Config.PSObject.Properties.Match('pairs')) {
        $Config | Add-Member -NotePropertyName 'pairs' -NotePropertyValue ([pscustomobject]@{full=@(); hints=@()})
    } else {
        if (-not $Config.pairs.PSObject.Properties.Match('full')) {
            $Config.pairs | Add-Member -NotePropertyName 'full' -NotePropertyValue @()
        }
        if (-not $Config.pairs.PSObject.Properties.Match('hints')) {
            $Config.pairs | Add-Member -NotePropertyName 'hints' -NotePropertyValue @()
        }
    }

    if (-not $Config.PSObject.Properties.Match('generated_pairs_file_path')) {
        $Config | Add-Member -NotePropertyName 'generated_pairs_file_path' -NotePropertyValue $null
    }
    if (-not $Config.PSObject.Properties.Match('includes')) {
        $Config | Add-Member -NotePropertyName 'includes' -NotePropertyValue @()
    }
    if (-not $Config.PSObject.Properties.Match('section_order')) {
        $Config | Add-Member -NotePropertyName 'section_order' -NotePropertyValue @()
    }
    if (-not $Config.PSObject.Properties.Match('extra_sections')) {
        $Config | Add-Member -NotePropertyName 'extra_sections' -NotePropertyValue @()
    }

    foreach ($hint in $Config.pairs.hints) {
        if (-not $hint.PSObject.Properties.Match('prefix')) {
            $hint | Add-Member -NotePropertyName 'prefix' -NotePropertyValue $null
        }
        if (-not $hint.PSObject.Properties.Match('postfix')) {
            $hint | Add-Member -NotePropertyName 'postfix' -NotePropertyValue $null
        }
        if (-not $hint.PSObject.Properties.Match('randomize')) {
            $hint | Add-Member -NotePropertyName 'randomize' -NotePropertyValue $null
        }
        if (-not $hint.PSObject.Properties.Match('random_charset')) {
            $hint | Add-Member -NotePropertyName 'random_charset' -NotePropertyValue $null
        }
    }
}

function Save-ConfigObject {
    param(
        [pscustomobject]$Config,
        [string]$Path
    )

    $lines = New-Object System.Collections.Generic.List[string]

    if ($Config.generated_pairs_file) {
        $lines.Add('[global]')
        $lines.Add("generated_entries_file=$($Config.generated_pairs_file)")
        $lines.Add('')
    }

    $sectionOrder = if ($Config.PSObject.Properties.Match('section_order')) { $Config.section_order } else { @() }
    $includesByName = @{}
    foreach ($inc in $Config.includes) {
        if (-not $includesByName.ContainsKey($inc.name)) {
            $includesByName[$inc.name] = New-Object System.Collections.Generic.List[pscustomobject]
        }
        $includesByName[$inc.name].Add($inc)
    }
    $fullMap = @{}
    foreach ($pair in $Config.pairs.full) {
        $n = if ($pair.name) { $pair.name } else { 'entry' }
        $isAuto = $false
        if ($pair.PSObject.Properties.Match('from_auto')) {
            $isAuto = [bool]$pair.from_auto
        }
        if ($Config.generated_pairs_file_path -and $isAuto) {
            continue
        }
        $fullMap[$n] = $pair
    }
    $hintMap = @{}
    foreach ($hint in $Config.pairs.hints) {
        $n = if ($hint.name) { $hint.name } else { 'entry' }
        $hintMap[$n] = $hint
    }
    $extraSectionsByName = @{}
    if ($Config.PSObject.Properties.Match('extra_sections')) {
        foreach ($extra in $Config.extra_sections) {
            if (-not $extraSectionsByName.ContainsKey($extra.name)) {
                $extraSectionsByName[$extra.name] = New-Object System.Collections.Generic.List[pscustomobject]
            }
            $extraSectionsByName[$extra.name].Add($extra)
        }
    }
    $directionWritten = $false

    function Write-DirectionSection {
        param(
            [System.Collections.Generic.List[string]]$Target,
            [pscustomobject]$Config
        )
        $markerLine = if ($Config.direction_markers.original) { $Config.direction_markers.original -join ',' } else { '' }
        $Target.Add('[direction_markers]')
        $Target.Add("original=$markerLine")
        $Target.Add('')
    }

    function Write-FullSection {
        param(
            [System.Collections.Generic.List[string]]$Target,
            $Pair,
            [string]$Name
        )
        $Target.Add("[full.$Name]")
        $Target.Add("original=$($Pair.original)")
        $Target.Add("anonymized=$($Pair.anonymized)")
        if (Test-ObjectDisabled $Pair) {
            $Target.Add('disabled=true')
        }
        $Target.Add('')
    }

    function Write-HintSection {
        param(
            [System.Collections.Generic.List[string]]$Target,
            $Hint,
            [string]$Name
        )
        $Target.Add("[hint.$Name]")
        $Target.Add("hint=$($Hint.hint)")
        if ($Hint.prefix) { $Target.Add("prefix=$($Hint.prefix)") }
        if ($Hint.postfix) { $Target.Add("postfix=$($Hint.postfix)") }
        if ($Hint.randomize) {
            $Target.Add("randomize=$($Hint.randomize)")
            if ($Hint.random_charset) { $Target.Add("random_charset=$($Hint.random_charset)") }
        } else {
            $widthValue = if ($Hint.width) { $Hint.width } else { 4 }
            $Target.Add("width=$widthValue")
            $nextValue = if ($Hint.next_index) { $Hint.next_index } else { 1 }
            $Target.Add("next_index=$nextValue")
            if ($Hint.random_charset) {
                $Target.Add("random_charset=$($Hint.random_charset)")
            }
        }
        if (Test-ObjectDisabled $Hint) {
            $Target.Add('disabled=true')
        }
        $Target.Add('')
    }

    function Write-GenericSection {
        param(
            [System.Collections.Generic.List[string]]$Target,
            [string]$Name,
            [hashtable]$Data
        )
        $Target.Add("[$Name]")
        foreach ($key in $Data.Keys) {
            $Target.Add("{0}={1}" -f $key, $Data[$key])
        }
        $Target.Add('')
    }

    foreach ($entry in $sectionOrder) {
        switch ($entry.kind) {
            'include' {
                if ($includesByName.ContainsKey($entry.name) -and $includesByName[$entry.name].Count -gt 0) {
                    $inc = $includesByName[$entry.name][0]
                    $includesByName[$entry.name].RemoveAt(0)
                    $lines.Add("[$($entry.name)]")
                    if (Test-ObjectDisabled $inc) {
                        $lines.Add('disabled=true')
                    }
                    if (-not $inc.implicit -and $inc.include_file) {
                        $lines.Add("include_file=$($inc.include_file)")
                    }
                    $lines.Add('')
                }
            }
            Default {
                $name = $entry.name
                if ($name -eq 'direction_markers') {
                    if (-not $directionWritten) {
                        Write-DirectionSection -Target $lines -Config $Config
                        $directionWritten = $true
                    }
                }
                elseif ($name -eq 'global') {
                    continue
                }
                elseif ($name -like 'full.*') {
                    $key = $name.Substring(5)
                    if ($fullMap.ContainsKey($key)) {
                        Write-FullSection -Target $lines -Pair $fullMap[$key] -Name $key
                        $null = $fullMap.Remove($key)
                    }
                }
                elseif ($name -like 'hint.*') {
                    $key = $name.Substring(5)
                    if ($hintMap.ContainsKey($key)) {
                        Write-HintSection -Target $lines -Hint $hintMap[$key] -Name $key
                        $null = $hintMap.Remove($key)
                    }
                }
                else {
                    if ($extraSectionsByName.ContainsKey($name) -and $extraSectionsByName[$name].Count -gt 0) {
                        $sectionData = $extraSectionsByName[$name][0]
                        $extraSectionsByName[$name].RemoveAt(0)
                        Write-GenericSection -Target $lines -Name $name -Data $sectionData.data
                    }
                }
            }
        }
    }

    if (-not $directionWritten) {
        Write-DirectionSection -Target $lines -Config $Config
    }

    foreach ($key in ($fullMap.Keys | Sort-Object)) {
        Write-FullSection -Target $lines -Pair $fullMap[$key] -Name $key
    }

    foreach ($key in ($hintMap.Keys | Sort-Object)) {
        Write-HintSection -Target $lines -Hint $hintMap[$key] -Name $key
    }

    foreach ($name in $extraSectionsByName.Keys) {
        foreach ($sectionData in $extraSectionsByName[$name]) {
            Write-GenericSection -Target $lines -Name $name -Data $sectionData.data
        }
    }

    $content = ($lines -join [Environment]::NewLine).TrimEnd()
    Set-Content -Path $Path -Value $content
}

function Get-DirectionFromMarkers {
    param(
        [string]$Text,
        [string[]]$Markers
    )

    if (-not $Markers -or $Markers.Count -eq 0) {
        return 'Unknown'
    }

    foreach ($marker in $Markers) {
        if ([string]::IsNullOrWhiteSpace($marker)) {
            continue
        }
        $pattern = [regex]::Escape($marker)
        if ([System.Text.RegularExpressions.Regex]::IsMatch($Text, $pattern, [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)) {
            return 'Original'
        }
    }

    return 'Unknown'
}

function Detect-DirectionFromFullPairs {
    param(
        [string]$Text,
        [object[]]$Pairs
    )

    if (-not $Pairs -or $Pairs.Count -eq 0) {
        return [pscustomobject]@{ Status = 'None'; OriginalMatches = @(); AnonymizedMatches = @() }
    }

    $originalSet = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
    $anonymSet = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

    foreach ($pair in $Pairs) {
        if (-not $pair) { continue }
        if (Test-ObjectDisabled $pair) { continue }
        if ($pair.original) {
            $pattern = [System.Text.RegularExpressions.Regex]::new([regex]::Escape($pair.original), [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
            if ($pattern.IsMatch($Text)) {
                $originalSet.Add([string]$pair.original) | Out-Null
            }
        }
        if ($pair.anonymized) {
            $matchValue = Get-AnonymizedOutputValue -Pair $pair
            $patternB = [System.Text.RegularExpressions.Regex]::new([regex]::Escape($matchValue), [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
            if ($patternB.IsMatch($Text)) {
                $anonymSet.Add([string]$matchValue) | Out-Null
            }
        }
    }

    $originalHit = $originalSet.Count -gt 0
    $anonymHit = $anonymSet.Count -gt 0
    $status = 'Unknown'
    if ($originalHit -and -not $anonymHit) { $status = 'Original' }
    elseif ($anonymHit -and -not $originalHit) { $status = 'Anonymized' }
    elseif ($originalHit -and $anonymHit) { $status = 'Ambiguous' }

    return [pscustomobject]@{
        Status = $status
        OriginalMatches = @($originalSet)
        AnonymizedMatches = @($anonymSet)
    }
}

function Apply-FullReplacements {
    param(
        [string]$InputText,
        [object[]]$Pairs,
        [ValidateSet('Original','Anonymized')]
        [string]$Direction
    )

    if (-not $Pairs) {
        return ,@($InputText, 0)
    }
    $result = $InputText
    $total = 0

    foreach ($pair in $Pairs) {
        if (-not ($pair.PSObject.Properties.Match('original') -and $pair.PSObject.Properties.Match('anonymized'))) {
            continue
        }
        if (Test-ObjectDisabled $pair) {
            continue
        }
        $anonymizedValue = Get-AnonymizedOutputValue -Pair $pair
        $from = if ($Direction -eq 'Original') { $pair.original } else { $anonymizedValue }
        $to = if ($Direction -eq 'Original') { $anonymizedValue } else { $pair.original }

        if ([string]::IsNullOrWhiteSpace($from) -or [string]::IsNullOrWhiteSpace($to)) {
            continue
        }

        $regex = [System.Text.RegularExpressions.Regex]::new([regex]::Escape($from), [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
        $matches = $regex.Matches($result)
        if ($matches.Count -eq 0) {
            continue
        }
        $result = $regex.Replace($result, $to)
        $total += $matches.Count
    }

    return ,@($result, $total)
}

function Get-NextHintValue {
    param([pscustomobject]$Hint)

    $width = if ($Hint.PSObject.Properties.Match('width') -and $Hint.width) { [int]$Hint.width } else { 4 }
    $next = if ($Hint.PSObject.Properties.Match('next_index') -and $Hint.next_index) { [int]$Hint.next_index } else { 1 }

    $value = $next.ToString(("D{0}" -f $width))
    $Hint.next_index = $next + 1
    return $value
}

function New-RandomString {
    param(
        [int]$Length,
        [string]$Charset = 'alnum'
    )

    if ($Length -le 0) {
        throw "randomize value must be >= 1"
    }

    $sets = @{
        'alpha' = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
        'alnum' = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
        'numeric' = '0123456789'
        'hex' = '0123456789abcdef'
    }

    $key = $Charset.ToLowerInvariant()
    if (-not $sets.ContainsKey($key)) {
        throw "Unsupported random_charset '$Charset'. Use alpha, alnum, numeric, or hex."
    }
    $chars = $sets[$key]
    $bytes = New-Object byte[] 1
    $builder = New-Object System.Text.StringBuilder
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        for ($i = 0; $i -lt $Length; $i++) {
            $rng.GetBytes($bytes)
            $index = $bytes[0] % $chars.Length
            $null = $builder.Append($chars[$index])
        }
    }
    finally {
        if ($rng) { $rng.Dispose() }
    }
    return $builder.ToString()
}

function Get-AnonymizedOutputValue {
    param($Pair)

    return $Pair.anonymized
}

function Apply-HintAnonymization {
    param(
        [string]$InputText,
        [object[]]$Hints,
        [pscustomobject]$Config,
        [ref]$ConfigChanged
    )

    if (-not $Hints) {
        return ,@($InputText, 0)
    }
    $result = $InputText
    $total = 0

    for ($i = 0; $i -lt $Hints.Count; $i++) {
        $entry = $Hints[$i]
        if (-not $entry) { continue }
        if (-not $entry.PSObject.Properties.Match('hint')) { continue }
        if (Test-ObjectDisabled $entry) { continue }

        $hintPattern = [string]$entry.hint
        if ([string]::IsNullOrWhiteSpace($hintPattern)) { continue }

        $useRandom = ($entry.PSObject.Properties.Match('randomize') -and $entry.randomize -and $entry.randomize -gt 0)
        if ($useRandom -and ($entry.PSObject.Properties.Match('next_index') -and $entry.next_index)) {
            throw "Hint '$($entry.name)' cannot define both randomize and next_index."
        }

        try {
            $regex = [System.Text.RegularExpressions.Regex]::new($hintPattern, [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
        }
        catch {
            throw "Ungültiges Regex in hint '$($entry.name)': $($_.Exception.Message)"
        }
        $matches = $regex.Matches($result)
        if ($matches.Count -eq 0) { continue }
        Write-Verbose ("[hint:{0}] matches={1}" -f $entry.name, $matches.Count)

        $uniqueOrder = New-Object System.Collections.Generic.List[string]
        $uniqueMap = @{}
        foreach ($m in $matches) {
            if (-not $m.Value -or $m.Value.Length -eq 0) { continue }
            $key = $m.Value.ToLowerInvariant()
            if (-not $uniqueMap.ContainsKey($key)) {
                $uniqueMap[$key] = $true
                $null = $uniqueOrder.Add($m.Value)
            }
        }

        foreach ($originalValue in $uniqueOrder) {
            $existingPair = Find-FullPairByOriginal -Pairs $Config.pairs.full -OriginalValue $originalValue
            if ($existingPair) {
                $replacement = $existingPair.anonymized
            } else {
                $prefixValue = if ($entry.prefix) { [string]$entry.prefix } elseif (-not $useRandom) { 'HINT' } else { '' }
                $postfixValue = if ($entry.postfix) { [string]$entry.postfix } else { '' }
                if ($useRandom) {
                    if (-not $entry.randomize) {
                        throw "Hint '$($entry.name)' requires randomize length when random mode is enabled."
                    }
                    $charsetValue = if ($entry.random_charset) { [string]$entry.random_charset } else { 'alnum' }
                    $baseRandom = New-RandomString -Length $entry.randomize -Charset $charsetValue
                    $replacement = $prefixValue + $baseRandom + $postfixValue
                } else {
                    $baseSequential = Get-NextHintValue -Hint $entry
                    $replacement = $prefixValue + $baseSequential + $postfixValue
                }
                Add-HintFullPair -Config $Config -OriginalValue $originalValue -AnonymizedValue $replacement -SourceHint $entry.name | Out-Null
                $ConfigChanged.Value = $true
            }

            $outputValue = $replacement
            $patternExact = [System.Text.RegularExpressions.Regex]::new([regex]::Escape($originalValue), [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
            $matchesExact = $patternExact.Matches($result)
            if ($matchesExact.Count -eq 0) {
                continue
            }
            Write-Verbose ("[hint:{0}] replacing {1} occurrences of {2} with {3}" -f $entry.name, $matchesExact.Count, $originalValue, $outputValue)
            $result = $patternExact.Replace($result, $outputValue)
            $total += $matchesExact.Count
        }
    }

    return ,@($result, $total)
}

function Get-DefaultConfigPath {
    return Join-Path -Path (Get-Location) -ChildPath 'deannon.ini'
}

$filesParam = if ($null -eq $File) { @() } else { [array]$File }
if ($filesParam.Length -eq 0) {
    throw 'Please specify at least one input file via -File/-f.'
}
$Files = $filesParam

$providedConfigExplicit = $PSBoundParameters.ContainsKey('Config')
$defaultConfigPath = Get-DefaultConfigPath

if (-not $Config) {
    if (Test-Path -Path $defaultConfigPath -PathType Leaf) {
        $Config = $defaultConfigPath
    } else {
        throw 'Missing -Config/-c and no deannon.ini in the current directory.'
    }
}

$configObject = Get-ConfigObject -Path $Config
Ensure-ConfigShape -Config $configObject
Write-Verbose ("Loaded {0} full pairs, {1} hints" -f $configObject.pairs.full.Count, $configObject.pairs.hints.Count)
$script:AutoGeneratedPairs = @()
if ($configObject.generated_pairs_file) {
    $autoFilePath = if ([System.IO.Path]::IsPathRooted($configObject.generated_pairs_file)) {
        $configObject.generated_pairs_file
    } else {
        Join-Path -Path (Split-Path -Path $Config -Parent) -ChildPath $configObject.generated_pairs_file
    }
    if (-not (Test-Path -Path $autoFilePath -PathType Leaf)) {
        try {
            New-Item -ItemType File -Path $autoFilePath -Force | Out-Null
        } catch {
            throw "Unable to create generated entries file '$autoFilePath': $($_.Exception.Message)"
        }
    }
    $sections = [ordered]@{}
    try {
        $rawAuto = Get-Content -Path $autoFilePath -Raw
        if (-not [string]::IsNullOrWhiteSpace($rawAuto)) {
            $autoResult = Read-IniSections -Path $autoFilePath
            $sections = $autoResult.map
        }
    } catch {
        throw "Unable to read generated entries file '$autoFilePath': $($_.Exception.Message)"
    }

    foreach ($sectionName in $sections.Keys) {
        if ($sectionName -notlike 'full.*') { continue }
        $section = $sections[$sectionName]
        if (-not ($section.Contains('original') -and $section.Contains('anonymized'))) { continue }
        $entryName = $sectionName.Substring(5)
        $entryObj = [pscustomobject]@{
            name = $entryName
            original = $section['original']
            anonymized = $section['anonymized']
            source = if ($section.Contains('source')) { $section['source'] } else { $null }
        }
        $script:AutoGeneratedPairs += $entryObj
        $configObject.pairs.full = @($configObject.pairs.full + [pscustomobject]@{
            name = $entryName
            original = $entryObj.original
            anonymized = $entryObj.anonymized
            from_auto = $true
            from_config = $false
        })
    }
    $configObject.generated_pairs_file_path = $autoFilePath
}
$configChanged = $false
$stats = @()

:FileLoop foreach ($file in $Files) {
    if (-not (Test-Path -Path $file -PathType Leaf)) {
        Write-Warning "File '$file' not found. Skipping."
        continue
    }

    $text = Get-Content -Path $file -Raw
    $directionInfo = Detect-DirectionFromFullPairs -Text $text -Pairs $configObject.pairs.full
    $directionStatus = $directionInfo.Status
    $direction = $null

    switch ($directionStatus) {
        'Original' { $direction = 'Original' }
        'Anonymized' { $direction = 'Anonymized' }
        'Ambiguous' {
            $origList = if ($directionInfo.OriginalMatches.Count -gt 0) { $directionInfo.OriginalMatches -join ', ' } else { 'n/a' }
            $anonList = if ($directionInfo.AnonymizedMatches.Count -gt 0) { $directionInfo.AnonymizedMatches -join ', ' } else { 'n/a' }
            if ($configObject.generated_pairs_file_path) {
                Write-Warning "File '$file' contains both original and anonymized tokens; assuming deanonymization due to generated entries. Originals: $origList | Anonymized: $anonList"
                $direction = 'Anonymized'
            } else {
                Write-Warning "File '$file' contains both original and anonymized tokens; skipping. Originals: $origList | Anonymized: $anonList"
                continue FileLoop
            }
        }
        'Unknown' {
            $markerDirection = Get-DirectionFromMarkers -Text $text -Markers $configObject.direction_markers.original
            if ($markerDirection -eq 'Original') {
                $direction = 'Original'
            } else {
                Write-Warning "Datei '$file' konnte keiner Richtung zugeordnet werden (keine passenden full-Paare)."
                continue FileLoop
            }
        }
        'None' {
            $markerDirection = Get-DirectionFromMarkers -Text $text -Markers $configObject.direction_markers.original
            if ($markerDirection -eq 'Original') {
                $direction = 'Original'
            } else {
                Write-Warning "Datei '$file' übersprungen: keine full-Paare konfiguriert und keine direction_markers gefunden."
                continue FileLoop
            }
        }
    }

    switch ($direction) {
        'Original' {
            $fullResult = Apply-FullReplacements -InputText $text -Pairs $configObject.pairs.full -Direction 'Original'
            $hintResult = Apply-HintAnonymization -InputText $fullResult[0] -Hints $configObject.pairs.hints -Config $configObject -ConfigChanged ([ref]$configChanged)
            $finalText = $hintResult[0]
            $fullCount = $fullResult[1]
            $hintCount = $hintResult[1]
            $mode = 'anonymized'
        }
        'Anonymized' {
            $fullResult = Apply-FullReplacements -InputText $text -Pairs $configObject.pairs.full -Direction 'Anonymized'
            $finalText = $fullResult[0]
            $fullCount = $fullResult[1]
            $hintCount = 0
            $mode = 'deanonymized'
        }
        Default {
            Write-Warning "Datei '$file' konnte nicht klassifiziert werden; überspringe."
            continue FileLoop
        }
    }

    if ($finalText -ne $text) {
        [System.IO.File]::WriteAllText($file, $finalText)
    }

    $stats += [pscustomobject]@{
        file = $file
        direction = $mode
        full = $fullCount
        hints = $hintCount
    }
}


if ($configChanged) {
    if ($configObject.generated_pairs_file_path) {
        Write-GeneratedPairs -Entries $script:AutoGeneratedPairs -AutoFile $configObject.generated_pairs_file_path
    }
    Save-ConfigObject -Config $configObject -Path $Config
}

foreach ($stat in $stats) {
    Write-Host ("[{0}] {1} replacements: full={2}, hints={3}" -f $stat.file, $stat.direction, $stat.full, $stat.hints)
}
